name = "Agrocosm"
uuid = "03150e84-a77a-4da1-94e0-c2afe2ed6c45"
authors = ["Yunan Lin"]
version = "1.0.0-DEV"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
SpeedyWeatherInternals = "34489162-d270-4603-8b96-37b04f830d73"
Terrarium = "80418d68-07fa-499d-ae2b-c12e531f5cd8"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
Terrarium = {path = "../Terrarium.jl"}

[compat]
DocStringExtensions = "0.9.5"
KernelAbstractions = "0.9"
Oceananigans = "0.110.9"
SpeedyWeatherInternals = "0.2.1"
Terrarium = "0.1"
Unitful = "1"
julia = "1.10"
